### ISSUE TITLE
Request Paystck integration to 3rd party

### ISSUE THREAD

**Issue by shalominlasu** [PaystackOSS/sample-movie-ticket#4]
Hi Damilola,
Please I would like to integrate paystack to a site don't know if you can be of help.

**Comment by damilola-paystack** [comment]
Hi @shalominlasu, 

Sure! It'll be a pleasure to help with your integration. However, this isn't the right medium to use. Kindly shoot us an email at support@paystack.com letting us know what you've done and the issue you're facing.

**Comment by shalominlasu** [comment]
Support have  other been able to get it to work.
Mr Usman spoke to me a while ago about it & said they will get back to me.
